config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic:true
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles=Article.all
  end

  def show
  end

  def new
    @article=Article.new
  end

  def create
    @article= Article.new(article_params)
    redirect_to @article if @article.save
  end

  def edit
  end

  def update
    redirect_to @article if @article.save(article_params)
  end

  def destroy
    redirect_to :back if @article.destroy
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_commentable

    def new
      @comment = Comment.new
    end

    def create
      @comment = @commentable.comments.new(comment_params)

      if @comment.save
        redirect_to :back, notice: 'Your comment was successfully posted!'
      else
        redirect_to :back, notice: "Your comment wasn't posted!"
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Article.find_by_id(params[:article_id]) if params[:article_id]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>
<hr>
<% @articles.each do |article| %>
  <p>
    <%= link_to(article.title, article.body, target: "_blank") %> - <%= link_to("Show Page", article) %>
    <%= link_to(article.title, article.body, target: "_blank") %> - <%= link_to("Show Page", article) %> | <%= link_to 'Destroy Article', article_path(article), method: :delete %> 
  </p>
<% end %>
<hr>
<%= link_to 'New Article', new_article_path, class: 'btn btn-primary' %>
<hr>

app/views/articles/new.html.erb
<%= form_for @article do |f|%>
<h4> Create New Article <h4>
<%= f.label :title%>
<%= f.text_field :title , :class => 'form-control'%>

<%= f.label :body%>
<%= f.text_area :body , :class => 'form-control'%><br>

<%= f.submit 'Create Article', :class => 'btn btn-primary' %>
<%end%>

app/views/articles/show.html.erb
<h4> Article Title: <%= @article.title %></h1><br/>
<%= @article.body %> <br>
<small>Submitted <%= time_ago_in_words(@article.created_at) %> ago</small>
<hr>

<%= link_to 'Back', articles_path, class: 'btn btn-primary' %>
<h3>Comments</h3>

  <%= form_for [@article, Comment.new] do |f| %>
  <%= f.text_area :body, placeholder: "Add a comment" , :class => 'form-control'%><br/>
  <%= f.submit "Add Comment", :class => 'btn btn-primary' %>
<% end %>

<ul>
  <%= render @article.comments %>
</ul>

app/views/comments/_comment.html.erb
<li>
  <%= comment.body %> -
  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>

  <%= form_for [comment, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a Reply" , :class => 'form-control'%><br/>
      <%= f.submit "Reply"  , :class => 'btn btn-primary'%>
      <% end %>

  <ul>
      <%= render comment.comments %>
  </ul>

</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="footerContainer">
		<p class="copyright">Interactive Article Application - Alpish Singhal</p>
	</div>
</footer>
<style type="text/css">
.footer {
position: fixed;
left: 0;
bottom: 0;
width: 100%;
background-color: black;
color: white;
text-align: center;
}
</style>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
<ul class="nav navbar-nav">
	<h1></h1>
</ul>
<ul class="hmenu">

</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container" style="border:1px solid #cecece;">

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>
<style type="text/css">
   body {
    padding-bottom: 70px !important;
    background-color: darkkhaki;
  }
</style>